import os
import pandas as pd
from datetime import datetime

RESULTS_DIR = "results"
OUTPUT_DIR = "docs/rankings"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Generate an index.md for GitHub Pages
index_content = """# MF Screener AI Rankings

Welcome to the automated rankings generated by MF Screener AI. These rankings are the composite output of evaluating historical NAV data through quantitative strategies designed by Claude, Gemini, GPT, and Grok.

## Strategy Performance (Rolling SIP XIRR)

"""

# Add XIRR Table if available
xirr_path = os.path.join(RESULTS_DIR, 'ranks', 'xirr.csv')
if os.path.exists(xirr_path):
    xirr_df = pd.read_csv(xirr_path)
    if not xirr_df.empty:
        latest_xirr = xirr_df.iloc[-1]
        date_str = latest_xirr['date']
        
        index_content += f"*Latest data as of: {date_str}*\n\n"
        index_content += "| Category | Composite Strategy XIRR | Benchmark XIRR | Benchmark |\n"
        index_content += "|---|---|---|---|\n"
        
        # Helper to format XIRR safely
        def fmt_xirr(val):
            return f"{val:.2f}%" if pd.notnull(val) else "N/A"

        small_cap = fmt_xirr(latest_xirr.get('Small Cap'))
        small_bench = fmt_xirr(latest_xirr.get('NIFTY Smallcap 250'))
        
        mid_cap = fmt_xirr(latest_xirr.get('Mid Cap'))
        mid_bench = fmt_xirr(latest_xirr.get('NIFTY Midcap 150'))
        
        total_market = fmt_xirr(latest_xirr.get('Total Market'))
        total_bench = fmt_xirr(latest_xirr.get('NIFTY 500'))
        
        multi_asset = fmt_xirr(latest_xirr.get('Multi Asset'))
        
        index_content += f"| **Small Cap** | {small_cap} | {small_bench} | NIFTY Smallcap 250 |\n"
        index_content += f"| **Mid Cap** | {mid_cap} | {mid_bench} | NIFTY Midcap 150 |\n"
        index_content += f"| **Total Market** | {total_market} | {total_bench} | NIFTY 500 |\n"
        index_content += f"| **Multi Asset** | {multi_asset} | N/A | (Mixed Asset) |\n\n"


index_content += "## Available Categories\n\n"

categories = []

for file in sorted(os.listdir(RESULTS_DIR)):
    if file.endswith(".csv") and "_" not in file:
        category_name = file.replace(".csv", "")
        categories.append(category_name)
        
        df = pd.read_csv(os.path.join(RESULTS_DIR, file))
        # Sort by total_rank to be safe
        if 'total_rank' in df.columns:
            df = df.sort_values(by='total_rank')
        
        # Limit to top 10 for the markdown page to keep it clean and indexable
        df_top = df.head(10).copy()
        
        # Format some columns if they exist
        cols_to_keep = ['total_rank', 'name', 'final_score', 'avg_cagr_3y']
        display_cols = ['Rank', 'Fund Name', 'Composite Score', '3Y CAGR (%)']
        
        # add model scores
        for model in ['Claude', 'GPT', 'Gemini', 'Grok']:
            col_name = f'score_{model}'
            if col_name in df_top.columns:
                cols_to_keep.append(col_name)
                display_cols.append(f'{model} Score')
        
        # Ensure we only select existing columns
        existing_cols = [c for c in cols_to_keep if c in df_top.columns]
        display_cols = [display_cols[i] for i, c in enumerate(cols_to_keep) if c in df_top.columns]
        
        df_display = df_top[existing_cols]
        df_display.columns = display_cols
        
        # Write to markdown
        md_file = os.path.join(OUTPUT_DIR, f"{category_name.lower().replace(' ', '-')}.md")
        
        date_str = datetime.now().strftime("%B %d, %Y")
        
        with open(md_file, "w") as f:
            f.write(f"# Top {category_name} Mutual Funds\n\n")
            f.write(f"*Last updated: {date_str}*\n\n")
            f.write(f"The following is the quantitative ranking of **{category_name}** mutual funds based on the multi-LLM consensus of Claude, Gemini, GPT, and Grok.\n\n")
            f.write("[Read our Methodology](../METHODOLOGY.md) to understand how these scores are calculated.\n\n")
            
            # Manual Markdown table generation
            header = "| " + " | ".join(display_cols) + " |\n"
            separator = "|" + "|".join(["---" for _ in display_cols]) + "|\n"
            f.write(header)
            f.write(separator)
            
            for _, row in df_display.iterrows():
                row_str = "| " + " | ".join([str(x) for x in row.values]) + " |\n"
                f.write(row_str)

            f.write("\n\n*Note: This is the top 10 list. For the complete dataset, refer to the project's repository results.*")
        
        index_content += f"- [{category_name} Rankings]({category_name.lower().replace(' ', '-')}.md)\n"

# Write index.md inside rankings folder
with open(os.path.join(OUTPUT_DIR, "index.md"), "w") as f:
    f.write(index_content)
    
print("Markdown rankings generated successfully.")
